# Generated by Django 4.1.7 on 2023-09-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.RenameField(
            model_name='storydb',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='storydb',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='storydb',
            name='subject',
        ),
    ]
