# Generated by Django 4.1.7 on 2023-10-03 15:36

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0002_delete_total_rename_content_storydb_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydb',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),

        ),
    ]
