# Generated by Django 4.1.7 on 2023-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0003_storydb_create_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryDb',
        ),
    ]
