# Generated by Django 4.1.7 on 2023-10-03 15:44

from django.db import migrations, models
import django.utils.timezone
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0006_alter_storydb_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydb',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
