# Generated by Django 4.1.7 on 2023-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0008_alter_storydb_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='textStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='StoryDb',
        ),
    ]
