# Generated by Django 4.1.7 on 2023-10-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0009_textstory_delete_storydb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textstory',
            name='create_date',
        ),
    ]
