# Generated by Django 4.1.7 on 2023-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimchi', '0011_textstory_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstory',
            name='block',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
